![imagen](./img/ejercicios.png)

## Ejercicio 1
Importa el módulo de `numpy` y obtén su versión.

In [4]:
import numpy as np
np.__version__

'2.4.2'

## Ejercicio 2
Crea un array de una dimensión que vaya de 0 a 9. Llamalo `my_array`

In [5]:
my_array = np.array([0,1,2,3,4,5,6,7,8,9])
my_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Ejercicio 3
Crea un array 3x3, que sea todo a True

In [6]:
array_true = np.array([[True, True, True], [True, True, True], [True, True, True]])
array_true
'''
array = np.ones((3,3), dtype = bool)
print(array)
'''

'\narray = np.ones((3,3), dtype = bool)\nprint(array)\n'

## Ejercicio 4
Extrae todos los impares de `my_array`

In [9]:
print(my_array % 2 != 0)
print(my_array)

[False  True False  True False  True False  True False  True]
[0 1 2 3 4 5 6 7 8 9]


## Ejercicio 5
En un nuevo array, sustituye todos los impares de `my_array` por -1

## Ejercicio 6
En un nuevo array, sustituye todos los impares de `my_array` por -1. Esta vez usa `where`

## Ejercicio 7
Convierte `my_array` en un nuevo array de dos dimensiones mediante `reshape`.

In [11]:
nuevo_array = my_array.reshape((2,2))

ValueError: cannot reshape array of size 10 into shape (2,2)

## Ejercicio 8
Concatena los siguientes arrays verticalmente

```Python
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
```

In [14]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
ab = np.concatenate([ab, ab])

NameError: name 'ab' is not defined

## Ejercicio 9
Concatena los siguientes arrays horizontamente

```Python
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
```

In [15]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
np.hstack([ab,a])

NameError: name 'ab' is not defined

## Ejercicio 10
Encuentra todos los elementos en común entre ambos arrays. [Para ello usa la función `intersect1d`](https://numpy.org/doc/stable/reference/generated/numpy.intersect1d.html)

```Python
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
```

## Ejercicio 11
Obtén la documentación acerca de la función `concatenate`

## Ejercicio 12
Crea un array unidimensional que vaya del 0 al 9. Llámalo `my_array`. 
1. Multiplica cada uno de los elementos de `my_array` por 10, en un nuevo array
2. Accede al primer elemento de `my_array`
3. Accede al último elemento de `my_array`
4. Imprime por pantalla los numeros del 1 al 7 de `my_array`

In [24]:
my_array = np.array([0,1,2,3,4,5,6,7,8,9])
print(my_array * 10)
print(my_array[0])
print(my_array[-1])
print(my_array[0:8])

[ 0 10 20 30 40 50 60 70 80 90]
0
9
[0 1 2 3 4 5 6 7]


## Ejercicio 13
Crea un array manualmente de tres filas por tres columnas. Llámalo `my_matrix`

In [26]:
my_matrix = np.identity(3)
my_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Ejercicio 14
Obtén la siguiente secuencia:

```Python
[ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49]
```

In [ ]:
a = np.arange(1, 50, 3)
a

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49])

## Ejercicio 15
Obtén la siguiente secuencia

```Python
[4., 3.75, 3.5 , 3.25, 3.  , 2.75, 2.5 , 2.25, 2., 1.75, 1.5 ,1.25]
```

In [13]:
a = np.arange(4, 1, -0.25)
a

array([4.  , 3.75, 3.5 , 3.25, 3.  , 2.75, 2.5 , 2.25, 2.  , 1.75, 1.5 ,
       1.25])

## Ejercicio 16
Lee la imagen "numpy.png" usando Pillow, y guárdala en un array.

In [ ]:
"""
from PIL import Image
var = Image.open('/.Img/xxx.png) - ruta de la imagen
var = np.array(var)
print(var)
"""

'\nfrom PIL import Image\nvar = Image.open\n'

## Ejercicio 17
Crea un array de 4x1. A continuación convierte el array a un 2x2

In [30]:
a = np.full((4,1),1)
b = a.reshape(2,2)
b

array([[1, 1],
       [1, 1]])

## Ejercicio 18
Crea una secuencia aleatoria. La secuencia se tiene que componer de 4 matrices de 5x3. Serían 3 dimensiones diferentes.

In [16]:
print(np.random.randint(1, 20, size = (4,5,3)))

[[[ 2 15  7]
  [12 11  3]
  [ 2 17  4]
  [18  2  4]
  [16  5 12]]

 [[16 17  5]
  [13 14 15]
  [19 12 10]
  [16  6 10]
  [13 13  2]]

 [[14 13 19]
  [13 16  8]
  [11 17 11]
  [14  9  4]
  [ 5 17 14]]

 [[ 2  6  2]
  [19  7  5]
  [10  2 19]
  [ 2 12 17]
  [ 2  8  6]]]


## Ejercicio 19
Crea una matriz de 10x1, toda ella compuesta por `False`. Después transformalo en un 2x5

In [31]:
a = np.full((10,1),False)
b = a.reshape(2,5)
b

array([[False, False, False, False, False],
       [False, False, False, False, False]])

## Ejercicio 20
Dado el siguiente array

```Python
x = np.random.randint(10, 20, size = (5,2,6))
```

1. ¿Cuántos elementos tiene el array?
2. ¿Cuántas dimensiones?
3. ¿Cuánta es la longitud cada dimensión?

In [34]:
x = np.random.randint(10, 20, size = (5,2,6))
print(x.size)
print(x.ndim)
print(x.shape)

60
3
(5, 2, 6)
